### ISSUE TITLE
JumpToSelection

### ISSUE THREAD

**Issue by kristimeculi** [iamvivekkaushik/DatePickerTimelineFlutter#28] opened 2020-04-13 12:24 UTC
**Is your feature request related to a problem? Please describe.**
The problem is in the beginning because users must go in the selected date when the DatePicker has appeared and for the moment we only can go in the selected date after we use _controller.jumpToSelection();  in DatePicker View.

**Describe the solution you'd like**
Maybe we can call _controller.jumpToSelection() in initState

**Comment by Ludwigvsch** [comment] 2020-04-22 17:48
Hi, I have the same problem but would love to use this package. 
How can I implement this?

**Comment by iamvivekkaushik** [comment] 2020-04-22 18:06
Hi, I haven't yet looked at the issue. I Will update once I do. Currently, you can't use the controller inside `initState()`

**Comment by Ludwigvsch** [comment] 2020-04-22 18:17
Hey thanks for the fast response, how can I use it? Can you provide me an example?

**Comment by SpajicM** [comment] 2020-04-23 21:22
I had the same issue, fixed by using `WidgetsBinding.addPostFrameCallback(() {})`

**Comment by Ludwigvsch** [comment] 2020-04-23 21:24
> I had the same issue, fixed by using `WidgetsBinding.addPostFrameCallback(() {})`

Can you give me an example of where to use this?

**Comment by Ludwigvsch** [comment] 2020-04-24 14:18
@SpajicM where do I need to use this is in my code?

**Comment by amith-patil** [comment] 2020-05-11 17:56
I noticed a weird issue where the jumpToSelection() function jumps to the date + 1 field on first run. 
for example, if the date is 11th, I call the jumpToSelection() via the controller using a button, the timeline will jump to the 12th. any idea why?

code is below : 
```child: DatePicker(
                          _startDate,
                          controller: _dpc,
                          initialSelectedDate: _selectedDate,
                          width: Size_Config.blockSizeHorizontal * 15,
                          height: Size_Config.blockSizeVertical * 12,
                          monthTextStyle: TextStyle(fontFamily: 'Montserrat',color: Colors.white54,fontSize: Size_Config.blockSizeHorizontal * 3),
                          dateTextStyle: TextStyle(fontFamily: 'MontSerrat',fontSize: Size_Config.blockSizeHorizontal * 5,fontWeight: FontWeight.bold,color: Colors.white54),
                          dayTextStyle: TextStyle(fontFamily: 'Montserrat',color: Colors.white54,fontSize: Size_Config.blockSizeHorizontal * 3),
                          onDateChange:(date) { _pc.open(); setState(() {
                            _selectedDate = date;
                          });},
                        ),


.......

child: IconButton(
                                 onPressed: () { _pc.close();_dpc.animateToSelection();},
                                  icon: Icon(CustomIcons.filter),
                                  color: Colors.white54,
                                  //iconSize: 40,
                                ),

**Comment by SpajicM** [comment] 2020-05-11 18:07
@amith-patil Timezones.

**Comment by amith-patil** [comment] 2020-05-11 18:11
> @amith-patil Timezones.

I'm not sure how that comes into the picture. Could you elaborate?

**Comment by SpajicM** [comment] 2020-05-11 18:19
@amith-patil alright, attach an example, I will look into it, but those off by one errors for me were often caused by time offset.

**Comment by amith-patil** [comment] 2020-05-11 18:45
I'm inclined to believe it's got something to do with the timestamp, because at midnight right now, it's jumping to the correct date. 

![ezgif-3-d1001ca39879](https://user-images.githubusercontent.com/51911194/81598827-87998300-93e5-11ea-9dce-313206427955.gif)

**Comment by amith-patil** [comment] 2020-05-11 18:47
also found this weird issue with the startDate

![ezgif-3-3c6cb3f8f3af](https://user-images.githubusercontent.com/51911194/81599028-d3e4c300-93e5-11ea-9b4b-fcdc723f441d.gif)

**Comment by SpajicM** [comment] 2020-05-11 18:52
To fix it, any set time to 00:00 on any DateTime instance you are using.

**Comment by amith-patil** [comment] 2020-05-11 18:57
> To fix it, any set time to 00:00 on any DateTime instance you are using.

gotcha. I figured that's where the issue was.

**Comment by iamvivekkaushik** [comment] 2020-05-11 19:17
Thanks for bringing this to the attention, I'll take a look at it and update you guys here.

**Comment by amith-patil** [comment] 2020-05-11 19:20
> Thanks for bringing this to my attention, I'll take a look at it and update you guys here.

Hey Vivek, I'm seeing the jump to be very unpredictable with the offset, I've tried to set the time to 00:00:00, but the start date still moves right to the next date.

**Comment by iamvivekkaushik** [comment] 2020-05-11 19:25
> > Thanks for bringing this to my attention, I'll take a look at it and update you guys here.
> 
> Hey Vivek, I'm seeing the jump to be very unpredictable with the offset, I've tried to set the time to 00:00:00, but the start date still moves right to the next date. 
> Do you want me to open this as a separate issue for you?
> ![ezgif-3-3c6cb3f8f3af](https://user-images.githubusercontent.com/51911194/81602687-ae0ded00-93ea-11ea-90e7-e60d3e714637.gif)
> 

Yes please, create a new issue.

**Comment by Ludwigvsch** [comment] 2020-06-04 12:20
How do I use the controller to see the right date when the screen loads, what argument needs it in init State, and how to use it, please help...

**Comment by amith-patil** [comment] 2020-06-04 12:30
> How do I use the controller to see the right date when the screen loads, what argument needs it in init State, and how to use it, please help...

You can use the controller to jump to the selected date when the screen loads

**Comment by Ludwigvsch** [comment] 2020-06-05 16:41
Thats the error message when using jumpToSelection

The method 'jumpToSelection' was called on null.
Receiver: null
Tried calling: jumpToSelection()

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      _Main_pageState.build.<anonymous closure> 
package:day_planner/screeens/mainpage.dart:218
#2      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:989
#3      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1095
#4      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#ea023
    debugOwner: GestureDetector
    state: possible

**Comment by rednikisfun** [comment] 2020-07-28 13:40
I have an issue which I think would be suitable here. I am trying to call _datePickerController.animateToDate(DateTime.now()); or _datePickerController.jumpToSelection(); in initState of the page, but get 

DatePickerController is not attached to any DatePicker View.
'package:date_picker_timeline/date_picker_widget.dart':
Failed assertion: line 201 pos 12: '_datePickerState != null'

I only show dates from 6 days before till today and need a way to show today which is in the end of the Date Picker.

**Comment by iamvivekkaushik** [comment] 2020-08-15 09:25
@rednikisfun you can use this

```dart
@override
void initState() {
    WidgetsBinding.addPostFrameCallback(() {
        // Do Something here
        _datePickerController.animateToDate(DateTime.now());
    })
}
```

**Comment by iamvivekkaushik** [comment] 2020-08-15 09:28
This issue is now fixed in the latest version.

**Closed by iamvivekkaushik** 2020-08-15 09:28 UTC
Labels: good first issue

**Comment by amiraaBetar** [comment] 2022-01-26 21:13
> This issue is now fixed in the latest version.

Can you explain to me how i can fix this problem because it dosen't work with me

**Comment by Meet-05** [comment] 2022-02-10 08:43
> the exact code that should work is
> 
> ```dart
>  WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
>    // Do Something here
>         _datePickerController.jumpToSelection();
>     });
> ```

Thanks! this worked.

**Comment by gamcho3** [comment] 2022-03-16 07:24
> the exact code that should work is
> 
> ```dart
>  WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
>    // Do Something here
>         _datePickerController.jumpToSelection();
>     });
> ```

Do you know how to focus center?
